AppBundle\Entity\Address:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: 255
            unique: false
        postalCode:
            type: string
            length: 255
            unique: false
            nullable: true
        street:
            type: string
            length: 255
            unique: false
            nullable: true
        city:
            type: string
            length: 255
            unique: false
            nullable: true
    lifecycleCallbacks: {  }
