AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        facebook:
            type: string
            length: 255
            nullable: true
        web:
            type: string
            length: 255
            nullable: true
        fax:
            type: string
            length: 255
            nullable: true
        mobilePhone:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
