AppBundle\Entity\UserBusiness:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserBusinessRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
